name: Bug Report
description: Create a report to help us improve
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: The description of the bug
      description: |
        Please describe the issue that you are experiencing that you wish to communicate with
        the maintainers. Tell us what you were trying to do and what happened.
        
        Provide a clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: The steps to roproduce the bug
      description: |
        Please describe the exact steps necessary to follow the to reproduce the bug that
        you experienced. For simple bugs this may not be required, but will help
        to ensure the bug will be fixed quicker and correctly.
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: false
