name: Bug Report
description: Create a report to help us improve
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: The description of the bug
      description: |
        Please describe the issue that you are experiencing that you wish to communicate with
        the maintainers. Tell us what you were trying to do and what happened.
        
        Provide a clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: The steps to roproduce the bug
      description: |
        Please describe the exact steps necessary to follow the to reproduce the bug that
        you experienced. For simple bugs this may not be required, but will help
        to ensure the bug will be fixed quicker and correctly.
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen instead of the bug?
      description: |
        Please describe what you expected to happen insead of the
        bug that you are reporting.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which Operating System are you using?
      description: |
        Please select the operating system that you experienced this bug on.
        Please also use Additional Details section to narrow down any CI
        or linux distro in use.
      options:
        - Windows 11
        - Windows 10
        - Windows 8.1
        - Winndows 8.0
        - Arch Linux
        - Debian/Ubuntu
        - Other Linux
        - Mac OSX
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: What version of [INPUT APP NAME HERE] did this bug appear on?
      description: |
        Please input the exact version of the application that you was
        running at the time this bug occurred. Feel free to add additional versions
        if they are known to have the bug as well.
  - type: markdown
    attributes:
      value: "## Additional information"
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
